# Generated by Django 3.2 on 2021-05-08 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0002_remove_registerperson_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargesheet',
            name='complaint_id',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='police_description',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='police_id',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='suspects_id',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='theories_id',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='witness_id',
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_Act',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_Charges',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_image',
            field=models.FileField(default=None, max_length=255, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_phone_no',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_section',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_typeofoffense',
            field=models.CharField(choices=[('SO', 'Summary offense'), ('IO', 'Indictable offense')], default='SO', max_length=20),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Accused_underwhatlaw',
            field=models.CharField(choices=[('State', 'State'), ('Act', 'Act'), ('Cwealth', 'CWealth'), ('Reg', 'Reg'), ('Other', 'Other')], default='State', max_length=10),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Assisting_officer',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_image',
            field=models.FileField(default=None, max_length=255, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_initial_report',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 4, 8, 25, 650013, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_phone_no',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Informant_signature',
            field=models.FileField(default=None, max_length=255, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Investigation_details',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Investigation_officer',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Issued_at',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Issued_when',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Reporting_officer',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Suspects',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theories',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witnesses',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='charging_officer',
            field=models.CharField(default='username', max_length=255),
        ),
    ]
