# Generated by Django 3.2 on 2021-05-08 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0003_auto_20210508_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesheet',
            name='Informant_initial_report',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Issued_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
