# Generated by Django 3.2 on 2021-05-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0006_auto_20210508_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_Act',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_Charges',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_email',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_image',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_phone_no',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_section',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_sex',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_typeofoffense',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Accused_underwhatlaw',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Assisting_officer',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_address',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_description',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_image',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_initial_report',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_name',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_phone_no',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Informant_signature',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Investigation_details',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Investigation_officer',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Issued_at',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Issued_when',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Reporting_officer',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Suspects',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Theories',
        ),
        migrations.RemoveField(
            model_name='chargesheet',
            name='Witnesses',
        ),
    ]
