# Generated by Django 3.2 on 2021-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0008_auto_20210508_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargesheet',
            name='Suspect1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Suspect2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Suspect3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Suspect4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Suspect5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theory1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theory2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theory3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theory4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Theory5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witness1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witness2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witness3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witness4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='Witness5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='registerperson',
            name='Person_DOB',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='registerperson',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='registerperson',
            name='nationality',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='registerperson',
            name='phonenumber',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='registerperson',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
