# Generated by Django 3.2 on 2021-05-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0009_auto_20210508_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerperson',
            name='email',
        ),
    ]
