# Generated by Django 3.2 on 2021-05-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0012_auto_20210508_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='complaint_id',
        ),
        migrations.AddField(
            model_name='police',
            name='Sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='officer_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='police',
            name='phonenumber',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='position',
            field=models.CharField(blank=True, choices=[('PC', 'police_constable'), ('INS', 'police_inspector'), ('ACP', 'Assistant_commisioner_of_police'), ('SP', 'Superintendent_police')], default=None, max_length=255, null=True),
        ),
    ]
