# Generated by Django 3.2 on 2021-05-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0013_auto_20210509_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reportagainst', models.CharField(blank=True, choices=[('Person', 'Person'), ('Organization', 'Organization')], default=None, max_length=255, null=True)),
                ('reportagaints_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reportagainst_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reporttagainst_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reporttagainst_phonenumber', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reportagainstsex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other'), ('NA', 'NA')], default='M', max_length=10, null=True)),
                ('eventdatetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('eventtype', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('eventaddress', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('eventdescription', models.TextField(default=None)),
                ('reportagainst_image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='uploads/')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.registerperson')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
