# Generated by Django 3.2 on 2021-05-09 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0014_auto_20210509_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='eventdatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
