# Generated by Django 3.2 on 2021-05-09 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0015_alter_report_eventdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='eventdatetime',
        ),
        migrations.AddField(
            model_name='report',
            name='eventdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
