# Generated by Django 3.2 on 2021-05-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0016_auto_20210509_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportagaints_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporttagainst_address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporttagainst_phonenumber',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='reportagainst_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportagainst_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportagainst_phonenumber',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
