# Generated by Django 3.2 on 2021-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0018_auto_20210509_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportagainst_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
