# Generated by Django 3.2 on 2021-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0019_alter_report_reportagainst_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inf_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='inf_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='inf_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='inf_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='inf_phonenumber',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='inf_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other'), ('NA', 'NA')], default='M', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_by_type',
            field=models.CharField(blank=True, choices=[('Person', 'Person'), ('Organization', 'Organization')], default=None, max_length=255, null=True),
        ),
    ]
