# Generated by Django 3.2 on 2021-05-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0020_auto_20210509_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Filed', 'Filed'), ('Dismissed', 'Dismissed')], default='Pending', max_length=255, null=True),
        ),
    ]
