# Generated by Django 3.2 on 2021-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0021_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportagainst_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
