# Generated by Django 3.2 on 2021-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0022_alter_report_reportagainst_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='eventdescription',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
