# Generated by Django 3.2 on 2021-05-10 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0024_alter_report_reportagainst_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witnesses',
            name='theory',
        ),
        migrations.AddField(
            model_name='witnesses',
            name='DOB',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='witnesses',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='witnesses',
            name='report_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='eventdescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='witnesses',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
