# Generated by Django 3.2 on 2021-05-10 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0025_auto_20210510_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspects',
            name='DOB',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='suspects',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='suspects',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suspects',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
