# Generated by Django 3.2 on 2021-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0026_auto_20210510_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspects',
            name='report_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
