# Generated by Django 3.2 on 2021-05-11 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0027_suspects_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='theories',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='theories',
            name='proposed_by_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theories',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='theories',
            name='against',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='theories',
            name='proposed_by',
            field=models.CharField(blank=True, choices=[('Witness', 'Witness'), ('Police', 'Police')], default=None, max_length=255, null=True),
        ),
    ]
