# Generated by Django 3.2 on 2021-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0028_auto_20210511_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='theories',
            name='report_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
