# Generated by Django 3.2 on 2021-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0031_auto_20210511_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation_report',
            name='assisting_officer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigation_report',
            name='first_officer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
