# Generated by Django 3.2 on 2021-05-12 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0034_auto_20210512_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Person'), (2, 'Police'), (3, 'Admin'), (4, 'Court')], default=3, max_length=10),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('court_type', models.CharField(blank=True, choices=[('High_Court', 'High_Court'), ('District_Court', 'District_Court'), ('Lower_Court', 'Lower_Court')], default=None, max_length=255, null=True)),
                ('admin', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
