# Generated by Django 3.2 on 2021-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0035_auto_20210512_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesheet',
            name='Accused_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Informant_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Informant_signature',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
