# Generated by Django 3.2 on 2021-05-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0037_chargesheet_informant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('court_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('court_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('court_type', models.CharField(blank=True, choices=[('High_Court', 'High_Court'), ('District_Court', 'District_Court'), ('Lower_Court', 'Lower_Court')], default=None, max_length=255, null=True)),
                ('final_hearing', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('first_hearing', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('def_id', models.IntegerField(blank=True, default=None, null=True)),
                ('def_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('def_DOB', models.DateField(blank=True, default=None, null=True)),
                ('def_person_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_person_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_person_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('def_person_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('def_person_DOB', models.DateField(blank=True, default=None, null=True)),
                ('def_person_charges', models.TextField(blank=True, default=None, null=True)),
                ('def_person_image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('pros_id', models.IntegerField(blank=True, default=None, null=True)),
                ('pros_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('pros_DOB', models.DateField(blank=True, default=None, null=True)),
                ('pros_person_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_person_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_person_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pros_person_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('pros_person_DOB', models.DateField(blank=True, default=None, null=True)),
                ('pros_person_desc', models.TextField(blank=True, default=None, null=True)),
                ('pros_person_image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('judge_id', models.IntegerField(blank=True, default=None, null=True)),
                ('judge_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('judge_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('judge_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('judge_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('judge_DOB', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criminal_id', models.IntegerField(blank=True, default=None, null=True)),
                ('crime_type', models.CharField(blank=True, choices=[('Personal_crime', 'Personal_crime'), ('Property_crime', 'Property_crime'), ('Inchoate_crime', 'Inchoate_crime'), ('Statutory_crime', 'Statutory_crime'), ('Financial_crime', 'Financial_crime'), ('Other_crime', 'Other_crime')], default=None, max_length=255, null=True)),
                ('crime_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('crime_desc', models.TextField(blank=True, default=None, null=True)),
                ('crime_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('crime_place', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('criminal_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('criminal_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('criminal_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('criminal_phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('criminal_DOB', models.DateField(blank=True, default=None, null=True)),
                ('criminal_image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('criminal_charges', models.TextField(blank=True, default=None, null=True)),
                ('criminal_sentence_duration', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('criminal_sentence_start', models.DateField(blank=True, default=None, null=True)),
                ('criminal_sentence_end', models.DateField(blank=True, default=None, null=True)),
                ('crime_type', models.CharField(blank=True, choices=[('Personal_crime', 'Personal_crime'), ('Property_crime', 'Property_crime'), ('Inchoate_crime', 'Inchoate_crime'), ('Statutory_crime', 'Statutory_crime'), ('Financial_crime', 'Financial_crime'), ('Other_crime', 'Other_crime')], default=None, max_length=255, null=True)),
                ('crime_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('crime_desc', models.TextField(blank=True, default=None, null=True)),
                ('crime_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('crime_place', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('jail_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jail_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('jail_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=255, null=True)),
                ('decision_reason', models.TextField(blank=True, default=None, null=True)),
                ('decision_desc', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
