# Generated by Django 3.2 on 2021-05-13 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0038_case_crime_criminal_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('DOB', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('DOB', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
