# Generated by Django 3.2 on 2021-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0039_attorney_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='Sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='Sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True),
        ),
    ]
