# Generated by Django 3.2 on 2021-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0040_auto_20210513_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='def_crime_type',
            field=models.CharField(blank=True, choices=[('Personal_crime', 'Personal_crime'), ('Property_crime', 'Property_crime'), ('Inchoate_crime', 'Inchoate_crime'), ('Statutory_crime', 'Statutory_crime'), ('Financial_crime', 'Financial_crime'), ('Other_crime', 'Other_crime')], default=None, max_length=255, null=True),
        ),
    ]
