# Generated by Django 3.2 on 2021-05-14 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0042_auto_20210514_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('jailer', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
