# Generated by Django 3.2 on 2021-05-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0043_jail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jail',
            name='admin',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
