# Generated by Django 3.2 on 2021-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0044_jail_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Person'), (2, 'Police'), (3, 'Admin'), (4, 'Court'), (5, 'Jail')], default=3, max_length=10),
        ),
    ]
