# Generated by Django 3.2 on 2021-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0045_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jail',
            name='jail_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jail',
            name='jail_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
