# Generated by Django 3.2 on 2021-05-14 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0047_auto_20210514_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('release_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('release_phone_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('release_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('release_DOB', models.DateField(blank=True, default=None, null=True)),
                ('release_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other'), ('NA', 'NA')], default='M', max_length=10, null=True)),
                ('release_dropcharges', models.TextField(blank=True, default=None, null=True)),
                ('release_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('release_place', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('release_type', models.CharField(blank=True, choices=[('Convicted', 'Convicted'), ('Innocent', 'Innocent')], default=None, max_length=255, null=True)),
            ],
        ),
    ]
