# Generated by Django 3.2 on 2021-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0049_auto_20210515_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Added', 'Added')], default='Sent', max_length=255, null=True),
        ),
    ]
