# Generated by Django 3.2 on 2021-05-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0050_criminal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='criminal_sentence_duration',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='criminal_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True),
        ),
    ]
