# Generated by Django 3.2 on 2021-05-15 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0051_auto_20210515_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criminal_id', models.IntegerField(blank=True, default=0, null=True)),
                ('jail_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cell_type', models.CharField(blank=True, choices=[('NC', 'normal_cell'), ('HSC', 'High_Security_cell'), ('IC', 'Isolation_cell'), ('EC', 'Execution_cell')], default=None, max_length=255, null=True)),
                ('cell_secion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cell_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
