# Generated by Django 3.2 on 2021-05-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0052_cell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='cell_secion',
            new_name='cell_section',
        ),
    ]
