# Generated by Django 3.2 on 2021-05-15 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0053_rename_cell_secion_cell_cell_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criminal_id', models.IntegerField(blank=True, default=0, null=True)),
                ('jail_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_type', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Mining', 'Mining'), ('Construction', 'Construction'), ('Agriculture', 'Agriculture')], default=None, max_length=255, null=True)),
                ('work_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('work_desc', models.TextField(blank=True, default=None, null=True)),
                ('work_duration', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('work_start_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('work_end_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='criminal',
            name='status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Added', 'Added'), ('Released', 'Released')], default='Sent', max_length=255, null=True),
        ),
    ]
