# Generated by Django 3.2 on 2021-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0054_auto_20210515_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Mining', 'Mining'), ('Construction', 'Construction'), ('Prison_support', 'Prison_support')], default=None, max_length=255, null=True),
        ),
    ]
