# Generated by Django 3.2 on 2021-05-16 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0056_criminal_status_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Person'), (2, 'Police'), (3, 'Admin'), (4, 'Court'), (5, 'Jail'), (6, 'Doctor')], default=3, max_length=10),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True)),
                ('admin', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
