# Generated by Django 3.2 on 2021-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0058_auto_20210516_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='previous_diseasesheight',
            new_name='previous_diseases',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='abornmalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
