# Generated by Django 3.2 on 2021-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0059_auto_20210516_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='previous_diseases',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
