# Generated by Django 3.2 on 2021-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0060_alter_healthrecord_previous_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='jail_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
