# Generated by Django 3.2 on 2021-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0061_healthrecord_jail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='criminal_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
