# Generated by Django 3.2 on 2021-05-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0062_healthrecord_criminal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
