# Generated by Django 3.2 on 2021-05-17 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0063_auto_20210516_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criminal_id', models.IntegerField(blank=True, default=None, null=True)),
                ('criminal_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('jail_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meeting_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meeting_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meeting_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], default='M', max_length=10, null=True)),
                ('meeting_phonenumber', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('meeting_image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='')),
                ('occupation_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('occupation_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('occupation_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('occupation_phoennumber', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meeting_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
