# Generated by Django 3.2 on 2021-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0064_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='occupation_phoennumber',
            new_name='occupation_phonenumber',
        ),
        migrations.AddField(
            model_name='meeting',
            name='criminal_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='criminal_relation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
