# Generated by Django 3.2 on 2021-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0065_auto_20210517_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Granted', 'Granted'), ('Denied', 'Denied')], default='Pending', max_length=255, null=True),
        ),
    ]
