# Generated by Django 3.2 on 2021-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0067_auto_20210518_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_actual_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
