# Generated by Django 3.2 on 2021-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0069_meeting_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
