# Generated by Django 3.2 on 2021-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0070_police_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='person_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
