# Generated by Django 3.2 on 2021-06-02 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0072_meeting_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
