# Generated by Django 3.2 on 2021-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0074_criminal_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='criminal_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
