# Generated by Django 3.2.4 on 2021-06-18 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0075_decision_criminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargesheet',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Informant_initial_report',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
