# Generated by Django 3.2.4 on 2021-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0076_auto_20210618_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesheet',
            name='Issued_when',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
