# Generated by Django 3.2.4 on 2021-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0077_alter_chargesheet_issued_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesheet',
            name='Accused_Charges',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Accused_DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chargesheet',
            name='Informant_DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
