# Generated by Django 3.2.4 on 2021-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0078_auto_20210618_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesheet',
            name='Accused_Act',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
