# Generated by Django 3.2.4 on 2021-06-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_management', '0079_alter_chargesheet_accused_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycheckup',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=255, null=True),
        ),
    ]
